notifications:
  email: false

env:
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks

script:
 - cabal-1.18 configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal-1.18 build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal-1.18 test
